Create main.yml
gravitee-io/graviteeio-cli pull request #19
Opened 2020-11-10 09:36 UTC by Shaker5191

2020-11-10 09:36 UTC, Shaker5191 commented
- الاسم: Gravitee.io - APIM - إعدادات تعريف واجهة برمجة تطبيقات Drive
  الاستخدامات: GGui/graviteeio-apim-api-definition-action@v0.1

2020-11-10 09:49 UTC, brasseld commented
Hi @Shaker5191 

What is the purpose of this PR?

2020-11-10 09:50 UTC, brasseld requested changes
Don't see the purpose of this PR

2020-11-12 09:19 UTC, GGui commented
I think, it is a mistake PR

2020-11-12 09:19 UTC, closed without merging